### ISSUE TITLE
Implement time zones support

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#1148]
Currently, none of the `CFTimeZone`, `NSTimeZone` and `TimeZone` types work in Foundation. This is caused by the fact that WASI doesn't ship time zone files. The big problem here is that `DateFormatter` depends on these types, which makes it impossible to print dates. We can use [an implementation based on `strftime`](https://github.com/swiftwasm/swift-corelibs-foundation/commit/6b45fcb8905fef2ebac49955684fff2652e3c393) as a workaround, but this needs a better solution long term.

I don't think that embedding time zone files in the distribution is a good option, on the other hand, JavaScript folks [have the same problem](https://stackoverflow.com/questions/37001869/how-to-get-time-zone-of-city-or-country-in-javascript).

**Comment by kateinoigakukun** [comment]
Implemented by using ICU data
