### ISSUE TITLE
ARKit 

### ISSUE THREAD

**Issue by unnanego** [swiftwasm/swift#1180]
Is it possible to access ARKit using WASM? If it is, how do I get started? As I understand, there's no instruction yet?

**Comment by MaxDesiatov** [comment]
Could you clarify what's your use case? ARKit API is only present on iOS, the only practical way to run WebAssembly on iOS is within browsers such as Mobile Safari, where ARKit is not accessible. I'm not sure why would you want to do that though. Why wouldn't you write a native Swift app that instead uses ARKit directly with no WebAssembly involved? You'd most probably get better performance too, especially as neither WebAssembly nor WASI have standardized multi-threading yet.

**Comment by unnanego** [comment]
There is huge benefit in using it in a browser, because nobody wants to install the app for a 30 seconds experience. This is why 8th wall, for example, charges its users an astonishing $3000 per month.
