### ISSUE TITLE
Use Xcode 12 in the Catalina GitHub Actions build

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#1330]
Latest upstream `master` apparently needs Xcode 12 beta to buld.

Currently blocked by https://github.com/actions/virtual-environments/issues/1133

**Comment by j-f1** [comment]
Seems like this has happened?

**Comment by MaxDesiatov** [comment]
Yes, thanks for the reminder! Resolved in https://github.com/swiftwasm/swift/pull/1289
