### ISSUE TITLE
Cannot run SwiftWasm on macOS 10.15

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/swift#1349]
I got this error after updating Tokamak to the latest SwiftWasm. Running macOS 10.15.5 (19F101).

```shellsession
$ carton dev --product TokamakDemo                                                                                                                                                                 
Polyfill integrity verified: /Users/jed/.carton/static/dev.js
Inferring basic settings...
- swift executable: /Users/jed/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-27-a/usr/bin/swift
Swift version 5.3-dev (LLVM a6315d2e8323dd3, Swift b80daa10576d040)
Target: x86_64-apple-darwin19.5.0
Parsing package manifest: /Users/jed/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-27-a/usr/bin/swift package dump-package
Error: Process failed with non-zero exit status and following error output:
/Users/jed/Documents/github-clones/Forks/Tokamak: error: manifest parse error(s):
Undefined symbols for architecture x86_64:
  "_$s18PackageDescription17SupportedPlatformV12MacOSVersionV6v10_15AEvau", referenced from:
      _main in Package-964a9c.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

**Comment by j-f1** [comment]
This error occurred after I deleted the `.build` directory due to this error:

```shellsession
$carton dev --product TokamakDemo
Polyfill integrity verified: /Users/jed/.carton/static/dev.js
Inferring basic settings...
- swift executable: /Users/jed/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-27-a/usr/bin/swift
Swift version 5.3-dev (LLVM a6315d2e8323dd3, Swift b80daa10576d040)
Target: x86_64-apple-darwin19.5.0
Parsing package manifest: /Users/jed/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-27-a/usr/bin/swift package dump-package
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.})))
````

**Comment by MaxDesiatov** [comment]
Thanks for reporting this, I'm waiting for CI to pass for #1289, hopefully it's fixed then or I'll tackle it in a separate PR.

**Comment by MaxDesiatov** [comment]
I also have a bit more hope for #1348 with the 5.3 release branch. It doesn't ship Foundation yet as far as I remember, but it should converge towards the 5.3 release in September/October, while `master` branch contains all the latest cutting edge hot stuff, which is obviously not so stable. And enabling Foundation in 5.3 release branch should be easier than resolving all the potential issues with `master`.

**Comment by j-f1** [comment]
It looks like the macOS build process crashed after failing to clone llvm

**Comment by MaxDesiatov** [comment]
Are you referring to a specific [GitHub Action run](https://github.com/swiftwasm/swift/actions) here?

**Comment by j-f1** [comment]
Yep! https://github.com/swiftwasm/swift/runs/831951677

**Comment by MaxDesiatov** [comment]
Ah, looks like an intermittent issue, I'll restart

**Comment by MaxDesiatov** [comment]
Now https://github.com/swiftwasm/swift/pull/1233 is the main to follow as it introduces automatic smoke testing of SwiftPM on CI.

**Comment by MaxDesiatov** [comment]
Ok, the tests fail for both 5.3 and dev snapshots, but for different reasons, gonna have a closer look tomorrow...

**Comment by MaxDesiatov** [comment]
The fix was merged today and should be included in the tonight's `2020-07-07` development snapshot, the work on fixing 5.3 snapshots is still in progress.
