### ISSUE TITLE
`if` does not work in a `ViewBuilder` body

### ISSUE THREAD

**Issue by carson-katri** [swiftwasm/swift#1379]
Currently if you try and use if, you are met with:

`Value of optional type 'view type?' must be unwrapped to a value of type 'view type'`

This can be resolved with an else statement, but then it crashes with:

`RuntimeError: memory access out of bounds`

**Comment by MaxDesiatov** [comment]
I can confirm that this issue is not related to the SwiftWasm toolchain, it was caused by `_ConditionalContent` body returning another `_ConditionalContent` view, which caused infinite recursion that in the end got reported as "memory access out of bounds".
