### ISSUE TITLE
Build broken by Apple Silicon patch

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#1388]
https://github.com/swiftwasm/swift/pull/1373

**Comment by MaxDesiatov** [comment]
This seems like a duplicate of #1385 to me.

**Comment by kateinoigakukun** [comment]
There was a build script issue that is not related to Xcode12. Please see the patch https://github.com/swiftwasm/swift/pull/1389/commits/9a99563c570e9b7da627159c2489af0974e766c2

**Comment by MaxDesiatov** [comment]
Awesome, many thanks for resolving it! I'll try to submit the patch upstream.

**Comment by MaxDesiatov** [comment]
@kateinoigakukun unless you'd like to submit the patch yourself 🙂

**Comment by kateinoigakukun** [comment]
@MaxDesiatov It would be really helpful for me if you can submit 🙏

**Comment by MaxDesiatov** [comment]
No problem at all, will do 👍

**Comment by MaxDesiatov** [comment]
Submitted as https://github.com/apple/swift/pull/32720
