### ISSUE TITLE
Upstream all the changes 🙌

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#187]
This issue is for tracking the overall progress of upstreaming our changes, please post here if you create any new PRs with our changes in [the upstream repository](https://github.com/apple/swift):

- [x] https://github.com/apple/swift/pull/24182
- [x] https://github.com/apple/swift/pull/24181
- [x] https://github.com/apple/swift/pull/24054
- [x] https://github.com/apple/swift/pull/29530
- [x] https://github.com/apple/swift/pull/29505
- [x] https://github.com/apple/swift/pull/29459
- [x] https://github.com/apple/swift/pull/29881
- [x] [stdlib] https://github.com/apple/swift/pull/29871
- [x] [stdlib] https://github.com/apple/swift/pull/39482
- [x] [SwiftPM] https://github.com/apple/swift-package-manager/pull/2735
- [x] [SwiftPM] https://github.com/apple/swift-package-manager/pull/2731
- [x] [SwiftPM] https://github.com/apple/swift-package-manager/pull/2734
- [x] [SwiftPM] https://github.com/apple/swift-package-manager/pull/2780
- [x] [SwiftPM] https://github.com/apple/swift-package-manager/pull/3819
- [x] [SwiftPM] https://github.com/apple/swift-package-manager/pull/2936
- [x] [LLVM] [**Support Swift calling convention for WebAssembly targets**](https://reviews.llvm.org/D71823). **Status: merged.**
- [x] [LLVM] [**Support swiftself and swifterror for WebAssembly target**](https://reviews.llvm.org/D76049). **Status: merged.**
- [x] [LLVM] [**Support single-floating-point immediate value**](https://reviews.llvm.org/D77384). **Status: merged.**
- [x] [LLVM] [**Emit PCH __clang_ast in custom section**](https://reviews.llvm.org/D74531). **Status: merged.**
- [x] https://github.com/apple/swift/pull/31678
- [x] https://github.com/apple/swift/pull/31672
- [x] https://github.com/apple/swift/pull/31691 **Status: rejected, reverted in our fork.**
- [x] https://github.com/apple/swift/pull/31695
- [x] https://github.com/apple/swift/pull/31674
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/2864
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/2867
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/2872
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/2873
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/2880
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3025
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3026
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3027
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3028
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3029
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3030
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3037
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3038
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3039
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3051
- [x] [Foundation] https://github.com/apple/swift-corelibs-foundation/pull/3050
- [x] [Frontend] https://github.com/apple/swift/pull/38805
- [x] [Build system] https://github.com/apple/swift/pull/39183
- [x] [Build system] https://github.com/apple/swift/pull/39275
- [x] [Build system] https://github.com/apple/swift/pull/39244
- [x] [Build system] https://github.com/apple/swift/pull/39274
- [x] [test] https://github.com/apple/swift/pull/39175
- [x] [Tools] https://github.com/apple/swift/pull/31920
- [x] https://github.com/apple/swift/pull/39359 **Status: in review.**
- [x] https://github.com/apple/swift/pull/41487
- [x] https://github.com/apple/swift/pull/42096
- [x] https://github.com/apple/swift/pull/24133 **Status: needs to be updated to emit each comdat in its own section.**
- [x] [IRGen] https://github.com/apple/swift/pull/30071 **Status: outdated.**
- [x] [Runtime] Disable exclusivity checking for WebAssembly https://github.com/apple/swift/pull/31693 **Status: needs updates after review.**
- [x] https://github.com/apple/swift/pull/31676 **Status: in review.**
- [x] https://github.com/apple/swift/pull/39502
- [x] https://github.com/apple/swift/pull/39504
- [x] https://github.com/apple/swift/pull/39546
- [x] https://github.com/apple/swift/pull/39361
- [x] https://github.com/apple/swift/pull/39583
- [x] https://github.com/apple/swift/pull/39483
- [x] https://github.com/apple/swift/pull/39519
- [x] https://github.com/apple/swift/pull/39680
- [x] https://github.com/apple/swift/pull/39299
- [x] https://github.com/apple/swift/pull/42094
- [x] https://github.com/apple/swift/pull/42095
- [x] https://github.com/apple/swift/pull/42097
- [x] https://github.com/apple/swift/pull/42155
- [x] https://github.com/apple/swift/pull/39300
- [x] https://github.com/apple/swift/pull/58514
- [x] https://github.com/apple/swift/pull/39119 **Status: in review.**
- [ ] [Driver]  https://github.com/apple/swift/pull/31912 **Status: needs updates after review**
- [ ] [Runtime] https://github.com/apple/swift/pull/31694 **Status: needs updates after review.**
- [ ] [ClangImporter] https://github.com/apple/swift/pull/31692 **Status: needs tests.**
- [ ] [ClangImporter] https://github.com/apple/swift/pull/31689 **Status: needs to be reverted in the fork and tested end-to-end with at least a few projects (especially those that ship C code).**
- [ ] [IRGen]  https://github.com/apple/swift/pull/24119 **Status: needs an update, atomics part probably can be upstreamed as a separate PR.**
- [ ] [BuildScript] https://github.com/apple/swift/pull/29465 **Status: needs conflicts resolved and potentially a different approach to this to be able to support Windows.**
- [ ] [SILOptimizer] **Status: needs a different approach that doesn't have as much impact on SIL.**
- [ ] https://github.com/apple/swift/pull/39360 **Status: in review.**

I think these capture only about a half of our changes, maybe much less, so more upstreaming effort is needed and welcome 🙏 

For upstreaming it's best to have a look at our umbrella PR https://github.com/apple/swift/pull/24684 and its diff and pick a self-contained and a relatively small patch that doesn't overlap or conflict with the rest of open PRs in the list above.

**Comment by karwa** [comment]
WRT the debugger tuning issue, it's possible this upstream patch might fix it: https://reviews.llvm.org/rG2504f14a06872f2e1755a88b3aab7e6bc280bec7

**Comment by MaxDesiatov** [comment]
That upstream patch did not come through. I'd appreciate it if anyone reading this pushed it forward 🙏 I'm myself is not an expert in that area.

**Comment by karwa** [comment]
@MaxDesiatov do you mean the debugging thing? I don’t know why the LLVM review thing says “audit required”, but it appears that it did land: https://github.com/apple/llvm-project/commit/2504f14a06872f2e1755a88b3aab7e6bc280bec7

**Comment by ephemer** [comment]
FYI `[LLVM] Support single-floating-point immediate value https://reviews.llvm.org/D77384. Status: been waiting for review for a month.` has landed. Looks like that's the only one in the list that hasn't been updated yet.

Maybe this is the wrong place to ask but how many of these tasks are critical for things to "just work" in SwiftWASM? As someone unfamiliar with the requirements of getting feature parity I find it hard to know which of the unmerged pieces need merging, and as such what is the most important / urgent subtask here. Or is this essentially a list of places where the SwiftWASM fork differs from the Apple repo, meaning the SwiftWASM fork has to be maintained separately until they are merged?

**Comment by MaxDesiatov** [comment]
> how many of these tasks are critical for things to "just work"

A lot of the things already work pretty well in our fork, or do you have some specific criteria for "just work" here?

>  Or is this essentially a list of places where the SwiftWASM fork differs from the Apple repo, meaning the SwiftWASM fork has to be maintained separately until they are merged?

Yes, that's the primary purpose of this issue. We have an "umbrella" https://github.com/apple/swift/pull/24684 PR, which stays open as an easy way to see the toolchain diff. There's no plan to merge or push that PR as is, we're only taking small chunks from it and submit as separate PRs, and those get added to the list here. Important to note that not everything from that diff has a corresponding upstream PR yet.

**Comment by kateinoigakukun** [comment]
Closing as all of the major patches are now upstreamed.
