### ISSUE TITLE
error in importing wasi binary into a Go application

### ISSUE THREAD

**Issue by hassan-shahbazi** [swiftwasm/swift#1880]
### Description
I have a Go application that uses _wasmer_ runtime to work with some wasi binaries. When I use Rust to write and generate wasm binary, I can access and use both _imported_ and _exported_ functions and it works perfectly fine.

``` go
import (
    wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)

func main() {
    bytes, error := wasm.ReadBytes("binary.wasm")
    if error != nil {
        panic(err)
    }

    instance, err := wasm.NewInstance(bytes)
    if err != nil {
        panic(err)
    }

    println("instance loaded!", instance)
}

```

However, when I try to import a binary generated by _swiftwasm_, it gives the following error:
```
Failed to instantiate the module:
            28 link errors: (1 of 28) Import not found, namespace: wasi_snapshot_preview1, name: proc_exit (2 of 28) Import not found, namespace: wasi_snapshot_preview1, name: args_sizes_get (3 of 28) Import not found, namespace: wasi_snapshot_preview1, name: args_get (4 of 28) Import not found, namespace: wasi_snapshot_preview1, name: sched_yield (5 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_read (6 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_write (7 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_close (8 of 28) Import not found, namespace: wasi_snapshot_preview1, name: clock_time_get (9 of 28) Import not found, namespace: wasi_snapshot_preview1, name: poll_oneoff (10 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_fdstat_get (11 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_open (12 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_filestat_get (13 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_rename (14 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_filestat_set_times (15 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_link (16 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_create_directory (17 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_readdir (18 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_readlink (19 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_symlink (20 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_prestat_get (21 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_prestat_dir_name (22 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_unlink_file (23 of 28) Import not found, namespace: wasi_snapshot_preview1, name: path_remove_directory (24 of 28) Import not found, namespace: wasi_snapshot_preview1, name: random_get (25 of 28) Import not found, namespace: wasi_snapshot_preview1, name: environ_sizes_get (26 of 28) Import not found, namespace: wasi_snapshot_preview1, name: environ_get (27 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_fdstat_set_flags (28 of 28) Import not found, namespace: wasi_snapshot_preview1, name: fd_seek
```

This is my swift file:
```swift
print("Hello World!")
```

and I use the following command to generate the _wasi_ binary, according to the [guide here](https://swiftwasm.github.io/swiftwasm-book/index.html)
```bash
$ TOOLCHAIN_PATH = $HOME/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-09-29-a/usr/share
$ swiftc -target wasm32-unknown-wasi -sdk $TOOLCHAIN_PATH/wasi-sysroot binary.swift -o binary.wasm
```

Also, running the binary directly with _wasmer_ does not have any issues:
```bash
$ wasmer binary.wasm
Hello World!
```

**Comment by MaxDesiatov** [comment]
Thanks for creating the issue! 5.3 snapshots should be more stable in general, do you get the same results with `wasm-5.3-SNAPSHOT-2020-09-28-a`?

My current hypothesis is that Rust binaries somehow don't link these symbols, and you need to configure Go Wasmer bindings to link with WASI symbols (those do look like WASI symbols to me). But I may be wrong, I never used Go Wasmer bindings before.

@kateinoigakukun have you seen any issues like this before?

**Comment by kateinoigakukun** [comment]
@hassan-shahbazi 
You need to use `InstantiateWithImportObject` instead of `NewInstance` to import wasi functions. Please refer to this example.


```go
package main

import (
	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)

func main() {
	bytes, _ := wasm.ReadBytes("hello.wasm")
	module, _ := wasm.Compile(bytes)
	wasiVersion := wasm.WasiGetVersion(module)
	importObject := wasm.NewDefaultWasiImportObjectForVersion(wasiVersion)
	instance, _ := module.InstantiateWithImportObject(importObject)
	defer instance.Close()

	instance.Exports["_start"]()
}
```

**Comment by MaxDesiatov** [comment]
Hassan, please let us know if that resolves your issue. 🙂

**Comment by hassan-shahbazi** [comment]
@kateinoigakukun 
Thanks for your help. I could import a swift binary wasm, however, using `wasm.Compile(bytes)` seems to make a significant performance cost. When I use `wasm.NewInstanceWithImports(bytes, imports)`, 10 tests run only in `0.632s` for a complex Rust binary, but with the `Compile` API, it takes `17.50s` to run a single test for a simple one-line Swift binary.
I'm wondering now how I can use _DefaultWasiImportObject_ without compiling the binary.

**Comment by kateinoigakukun** [comment]
@hassan-shahbazi SwiftWasm uses `wasi_snapshot1_preview` version of wasi module. So if you can assume that the input wasm binary is always Swift binary, you can create wasi import object by `wasm.NewDefaultWasiImportObjectForVersion(wasm.Snapshot1)`.


But I'm not well sure how to use the wasmer-go, so please open an issue on wasmer-go repo and ask them.

**Comment by hassan-shahbazi** [comment]
@kateinoigakukun and @MaxDesiatov  
Thanks for you incredible helps. Despite the performance costs, it seems that it works fine now. 
However, I cannot have access to any public functions on the Swift file except for `_start()` which looks to run the swift file. Do we have any examples about how to export/import functions? Something like the example for Rust here: https://github.com/wasmerio/wasmer-go#imported-function

**Comment by kateinoigakukun** [comment]
@hassan-shahbazi 



You can expose a Swift function for host environment using special attribute and linker option.

```swift
@_cdecl("add")
func add(_ lhs: Int, _ rhs: Int) -> Int {
    return lhs + rhs
}
```

You need to compile the Swift code with linker option `--export`.

```bash
$ TOOLCHAIN_PATH=$(dirname $(swiftenv which swiftc))/../
$ swiftc \
    -target wasm32-unknown-wasi \
    -sdk $TOOLCHAIN_PATH/share/wasi-sysroot \
    lib.swift -o lib.wasm \
    -Xlinker --export=add
```

Then, you can use the exported function from host environment.

```javascript
const WASI = require("@wasmer/wasi").WASI;
const WasmFs = require("@wasmer/wasmfs").WasmFs;

const promisify = require("util").promisify;
const fs = require("fs");
const readFile = promisify(fs.readFile);

const main = async () => {
  // Instantiate a new WASI Instance
  const wasmFs = new WasmFs();
  let wasi = new WASI({
    args: [],
    env: {},
    bindings: {
      ...WASI.defaultBindings,
      fs: wasmFs.fs,
    },
  });

  const wasmBinary = await readFile("lib.wasm");

  // Instantiate the WebAssembly file
  let { instance } = await WebAssembly.instantiate(wasmBinary, {
    wasi_snapshot_preview1: wasi.wasiImport,
  });
  // Get the exported function
  const addFn = instance.exports.add;
  console.log("2 + 3 = " + addFn(2, 3))

};

main()
```

If you use SwiftPM package, you can omit linker flag using clang's `__atribute__`. Please see [swiftwasm/JavaScriptKit#91](https://github.com/swiftwasm/JavaScriptKit/pull/91/files) for more detail info

**Comment by hassan-shahbazi** [comment]
@kateinoigakukun 
Awesome update, thanks a million. I could successfully call exposed Swift functions in my Go application.
 If I'm not mistaken, this is an example of _exported functions_ where the host env calls functions from the binary. But what about _imported functions_ where the binary calls functions from the env? This is done by defining `extern` functions in Rust as described in the link I had posted: https://github.com/wasmerio/wasmer-go#imported-function

**Comment by MaxDesiatov** [comment]
You'll have to declare your functions in a header file and provide a module map file. You can find an example [in JavaScriptKit](https://github.com/swiftwasm/JavaScriptKit/tree/main/Sources/_CJavaScriptKit/include), which consumes JavaScript functions from browser hosts that are [defined in the runtime part of JavaScriptKit](https://github.com/swiftwasm/JavaScriptKit/blob/main/Runtime/src/index.ts).

**Comment by MaxDesiatov** [comment]
Another option is to use [the `@_silgen_name` attribute](https://github.com/swiftwasm/swiftwasm-book/pull/3/files#diff-a8a5eeb68de1c383c01036100637f2be), but this attribute is underscored, which means it can go away in future versions of Swift. I feel that a separate target with a header and a module map is safer from that perspective. @kateinoigakukun maybe both approaches should be documented in the SwiftWasm book?

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Yes, both approaches should be documented. But I think we should provide a safe way to extern a Swift function without C code in the near future.

**Comment by MaxDesiatov** [comment]
Are you referring to what I mentioned in #1503 previously?

**Comment by kateinoigakukun** [comment]
Or if we can provide a similar feature like Clang's `__attribute__((__import_name__))`

**Comment by hassan-shahbazi** [comment]
@MaxDesiatov 
Thanks for references to documents. In my case, using `@_silgen_name` should be enough. I tried to follow document for [imported functions](https://github.com/swiftwasm/swiftwasm-book/blob/76b2e76bb20cf28e470351be1ffa5d625a2cb8c8/src/examples/importing-function.md) using the following code
```swift
@_silgen_name("runtime_ping")
func runtime_ping()
```
building by `swift build --triple wasm32-unknown-wasi -c release --toolchain $TOOLCHAIN_PATH -Xlinker --allow-undefined`, I get the error from my Go application that says the binary doesn't have a function with name _ping_:
```
The function with name ping was not found on the binary
```

Then, I tried to expose it using the same approach for exported functions
```swift
@_cdecl("ping")
func ping() { runtime_ping() }

@_silgen_name("runtime_ping")
func runtime_ping()
```

building with `swift build --triple wasm32-unknown-wasi -c release --toolchain $TOOLCHAIN_PATH -Xlinker --allow-undefined -Xlinker --export=ping`, I get the following error
```
This is a void function
SIGABRT: abort
PC=0x7f449d33518b m=0 sigcode=18446744073709551610

goroutine 7 [running]:
runtime: unknown pc 0x7f449d33518b
stack: frame={sp:0xc0000097d0, fp:0x0} stack=[0xc00004c000,0xc00004d000)

runtime: unknown pc 0x7f449d33518b
stack: frame={sp:0xc0000097d0, fp:0x0} stack=[0xc00004c000,0xc00004d000)

created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1178 +0x386

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000134000, 0x55e675, 0x1e, 0x5635e8, 0x482b01)
        /usr/local/go/src/testing/testing.go:1179 +0x3ad
testing.runTests.func1(0xc000001980)
        /usr/local/go/src/testing/testing.go:1449 +0x78
testing.tRunner(0xc000001980, 0xc00004bde0)
        /usr/local/go/src/testing/testing.go:1127 +0xef
testing.runTests(0xc00000e0e0, 0x62c6e0, 0x2, 0x2, 0xbfd6e263d8af437a, 0x8bb2d4cf90, 0x645c40, 0x411c50)
        /usr/local/go/src/testing/testing.go:1447 +0x2e8
testing.(*M).Run(0xc000112000, 0x0)
        /usr/local/go/src/testing/testing.go:1357 +0x245
main.main()
        _testmain.go:45 +0x138

rax    0x0
rbx    0x7f449d16fdc0
rcx    0x7f449d33518b
rdx    0x0
rdi    0x2
rsi    0xc0000097d0
rbp    0xc000009aa0
rsp    0xc0000097d0
r8     0x0
r9     0xc0000097d0
r10    0x8
r11    0x246
r12    0xffffffffffffffff
r13    0x2
r14    0xb
r15    0x1c
rip    0x7f449d33518b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

I use the approach explained [here](https://github.com/wasmerio/wasmer-go#imported-function) to import functions and it works OK with Rust.

**Comment by MaxDesiatov** [comment]
@hassan-shahbazi I'm sorry about these issues, I'd be happy to help in fixing those if these are reproducible. At the moment I'm not quite sure where exactly you'd like `ping` and `runtime_ping` to be defined. Would you be able to create a separate project on GitHub that reproduces the issue in isolation? I then would be able to have a detailed look.

**Comment by hassan-shahbazi** [comment]
Thanks for your help, I could find and fix the issue just now. The main problem was that the signatures did not match between the function defined in the c header file, and the one that was injected by the wasmer. I will close the issue

**Comment by MaxDesiatov** [comment]
No problem, thank you for reporting, it definitely did expose some missing areas in our documentation 🙂
