### ISSUE TITLE
Consider implementing threads support

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#1887]
I'm not 100% sure if everything is available in LLVM at this point (I've only found https://reviews.llvm.org/D57874 and https://reviews.llvm.org/D64537 so far), but [all browsers except Safari](https://webassembly.org/roadmap/) have support for WebAssembly threading and atomics now. It's time to start thinking about adding support for it in SwiftWasm.

I wonder if this is blocked by https://github.com/WebAssembly/wasi-libc/issues/209, or can we rely on those multi-threading APIs without pthreads?

We also need to clarify if WebAssembly platform in SwiftPM should have versions so that users declare compatibility with new WebAssembly features in their `Package.swift`? How should we name those versions? `.wasi(.mvp)` and `.wasi(.threads)`, but then the latter implies that WASI itself supports threads, and yet it doesn't. Maybe we should rely on year-based versioning approach, similar to what babel did with EcmaScript features versioning? Like `.wasi(.year2020)` for our current feature set w/o threads, and `.wasi(.year2021)` for the future release with threading support? (Exact names for these year-based version cases requires more bikeshedding).

**Comment by kateinoigakukun** [comment]
I think we need to provide a way to enable various features on wasm.
If thread feature is enabled, we need to link thread enabled version wasi-libc. And if thread feature is disabled, we need to link no-thread version wasi-libc. And we have to provide so many prebuilt wasi-libc libraries for each combinations of features.

**Comment by MaxDesiatov** [comment]
And then prebuilt stdlib and runtime with and without threading and atomics. 🤔 Maybe separate SwiftWasm distributions so that we don't blow up the distribution size?

**Comment by kateinoigakukun** [comment]
If we can remove wasi dependency from our toolchain and provide wasi-libc as SwiftPM package, the distribution issue would be resolved, I think.

**Comment by MaxDesiatov** [comment]
Foundation (and transitively XCTest) still depend on wasi-libc, even if we remove it from runtime and stdlib. I wish Foundation and XCTest were just SwiftPM packages 😔

**Comment by MaxDesiatov** [comment]
There's also Dispatch, which is also a part of the standard SDK and isn't distributed via SwiftPM.

**Comment by kateinoigakukun** [comment]
Hmm, I think Foundation can't provide threading API until wasm thread will be standardized 😢 .

**Comment by MaxDesiatov** [comment]
The proposal is in the "Proposed Spec Text Available (CG + WG)" stage, and would Foundation expose any platform-specific stuff? Wouldn't we hide it in Foundation under [the `Thread` API](https://developer.apple.com/documentation/foundation/thread) and `DispatchQueue` in Dispatch?

**Comment by kateinoigakukun** [comment]
> Wouldn't we hide it in Foundation under the Thread API and DispatchQueue in Dispatch?

I think if the linked binary has any thread related instruction, the runtime that doesn't support thread feature will crash.

**Comment by MaxDesiatov** [comment]
For future reference, [here's a ticket for `SharedArrayBuffer` support in WebKit](https://bugs.webkit.org/show_bug.cgi?id=212069), whcih is one of the things blocking us.

**Comment by yonihemi** [comment]
Have we seen this before? As of [Release 117](https://developer.apple.com/safari/technology-preview/release-notes/#r117) Safari Technology Preview supports Wasm threading (SharedArrayBuffer, Atomics, shared Wasm memory) behind a feature flag!
<img width="1310" alt="Safari TP wasm roadmap" src="https://user-images.githubusercontent.com/2340723/107850164-59951380-6e3b-11eb-86a5-08119fd5c1da.png">


To check it out run
```sh
__XPC_JSC_useSharedArrayBuffer=1 open -a "Safari Technology Preview"
```

**Comment by MaxDesiatov** [comment]
Great news, I hope it's shipped this year in Safari 15 enabled by default.

I'm still not sure what's the plan in WASI for threads and whether enabling pthreads is something they're interested in. Maybe we'll have to spawn workers and add shared memory boilerplate on our side instead? 🤔

**Comment by kateinoigakukun** [comment]
The latest status will be tracked in https://github.com/swiftwasm/swift/issues/5548
