### ISSUE TITLE
Remove wasi-sdk dependency

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#1888]
We can remove wasi-sdk dependency because we now ship self-built lld and clang instead of wasi-sdk version.

**Comment by MaxDesiatov** [comment]
Don't we use wasi-libc from the wasi-sdk archive, or do you mean that we should build wasi-libc as a part of our CI process in this repository too?

**Comment by kateinoigakukun** [comment]
I'm planning to setup CI on wasi-libc and use the prebuilt wasi-libc binary.

**Comment by kateinoigakukun** [comment]
I tackled this issue today, but I found that we need libcxx that comes from wasi-sdk.
The wasi-libc doesn't provide C++ stdlib header but we need them to build Swift stdlib.
