### ISSUE TITLE
Set vendor name for --version command

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swift#1907]
We should set vendor name to distinguish our toolchain from official one.

https://github.com/apple/swift/blob/f190342b617f42f2ae0248dfd51233c36d6db773/lib/Basic/Version.cpp#L399-L401

Expected output:

```bash
$ swift --version
SwiftWasm Swift version 5.3-dev (LLVM ba56ef042e, Swift 5855a96018)
Target: x86_64-apple-darwin19.3.0
```

**Comment by MaxDesiatov** [comment]
How would we also make it say `5.3.0` instead of `5.3-dev` when we tag that release? I thought this was included in `SWIFT_USER_VISIBLE_VERSION`, but the `-dev` part isn't there.

**Comment by kateinoigakukun** [comment]
I think if we set `SWIFT_COMPILER_VERSION`, the -dev suffix will be disappeared.
