### ISSUE TITLE
5.3 builds aren't automatically uploaded

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#2052]
I previously uploaded them manually when the nightly CI job failed, but it's not that easy with codesigning anymore. We need to make the cron job more reliable, as these failures are disruptive.

**Comment by kateinoigakukun** [comment]
Currently, I used my personal private key to sign the toolchain. Should we share the private key with organization members?

**Comment by kateinoigakukun** [comment]
Maybe we can use https://github.com/1Password/1password-teams-open-source

**Comment by MaxDesiatov** [comment]
Thanks for setting the codesigning up! No need to share the key, it's already stored in GitHub Secrets. And the issue is not with codesigning itself, but with the distribution script. I can debug it with a separate PR/branch instead of local runs, without waiting for the cron job to complete. 🙂

**Comment by kateinoigakukun** [comment]
@MaxDesiatov I fixed the distribution script and uploaded 5.3 build from my local machine

**Comment by MaxDesiatov** [comment]
Jolly good! 👍 I'll keep an eye on the 5.3 distribution script in the next few days (if we'll have any more snapshots then) and will reopen this if needed.

**Comment by MaxDesiatov** [comment]
Thanks again for your help, much appreciated! 👏
