### ISSUE TITLE
Mismatch in import signatures between SwiftWasm module and host function

### ISSUE THREAD

**Issue by cohix** [swiftwasm/swift#2111]
I'm seeing some odd behaviour when using Wasmer (via the Go extension) to host a module built with SwiftWasm.

I have this function (exposed via CGo):
```c
extern void print(void *context, int32_t pointer, int32_t size, int32_t ident);
```

With the Go signature:
```golang
func print(context unsafe.Pointer, pointer int32, size int32, identifier int32)
```

And I am declaring it my Swift file as:
```swift
@_silgen_name("print")
func print_msg(pointer: UnsafeRawPointer, size: Int32, ident: Int32)
```

However when I attempt to call this function from the Swift module, I get this error:
`link error: Incorrect import signature, namespace: env, name: print, expected signature: [I32, I32, I32, I32, I32] -> [], found signature: [I32, I32, I32] -> []`

The Swift module seems to expect a function with 5 arguments rather than 3.

If I modify the host functions as such:
```c
extern void print(void *context, int32_t pointer, int32_t size, int32_t ident, int32_t x, int32_t y);
```
And Go:
```golang
func print(context unsafe.Pointer, pointer int32, size int32, identifier int32, x int32, y int32)
```

Then everything works. Both of the extra params get value `0` and I can't seem to concoct a Swift function signature where this doesn't happen.

Please advise!

P.S. Otherwise things are working great! Thanks very much for the hard work!

**Comment by kateinoigakukun** [comment]
Sorry for confusing you. Swift default uses swiftcc (Swift Calling Convention) and it requires having `swiftself` and `swifterror` arguments on wasm even if the function is not throwable. Please see https://github.com/WebAssembly/tool-conventions/blob/master/SwiftABI.md

I recommend using `@_cdecl` instead of `@_silgen_name` to make the function to have C Calling Convention.

**Comment by MaxDesiatov** [comment]
But `@_cdecl` is meant to be used only for exported functions, not imported ones, isn't it?

**Comment by kateinoigakukun** [comment]
Yes, we should add a way to import functions as C function without C code. Until that, we need to use C module with SwiftPM.

**Comment by MaxDesiatov** [comment]
We shouldn't recommend `@_silgen_name` for [importing functions in the SwiftWasm book](https://book.swiftwasm.org/examples/importing-function.html) then, right?

**Comment by kateinoigakukun** [comment]
Absolutely right.

**Comment by cohix** [comment]
@MaxDesiatov The context param is used by the Wasmer Go extension and is not exposed to the module, I should have mentioned that in the issue.

Thanks for the explanation! Can we leave this open until a new annotation exists for importing a C-Style function?

**Comment by MaxDesiatov** [comment]
I think it's more related to #1503, but I'll keep this one open until we update the documentation.

**Comment by cohix** [comment]
Fair enough, thanks for taking a look.

**Comment by MaxDesiatov** [comment]
No problem, let us know if you have any other problems, questions or suggestions!
