### ISSUE TITLE
LinkError in Hello World Project

### ISSUE THREAD

**Issue by chfanghr** [swiftwasm/swift#2284]
Tried running the Hello World project but failed with the following linkage error:

Chrome(87.0.4280.67):
![image](https://user-images.githubusercontent.com/40087668/100990548-f4948600-358c-11eb-9c93-20b6c26fa41f.png)

Safari(14.0.1 (16610.3.6.3)):
![image](https://user-images.githubusercontent.com/40087668/100990623-0c6c0a00-358d-11eb-968c-18dc839620bc.png)

And wasmer(0.16.2):
```
❯ wasmer Bundle/17a2b2e670c505f8.wasm
Error: Can't instantiate module: LinkError([ImportNotFound { namespace: "wasi_snapshot_preview1", name: "proc_exit" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_create_typed_array" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_call_new" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_release" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_call_throwing_new" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_call_function_with_this" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_call_function" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_create_function" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_get_subscript" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_instanceof" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_decode_string" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_encode_string" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_load_string" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_get_prop" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_set_prop" }, ImportNotFound { namespace: "javascript_kit", name: "swjs_set_subscript" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "args_sizes_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "args_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_read" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_write" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_close" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_fdstat_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "path_open" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_prestat_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_prestat_dir_name" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "random_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "environ_sizes_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "environ_get" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_fdstat_set_flags" }, ImportNotFound { namespace: "wasi_snapshot_preview1", name: "fd_seek" }])
```

Seems like that jskit and wasi runtime is not ran correctly.

**Comment by chfanghr** [comment]
`carton test` failed as well, with the following output:
```
Dependency integrity verified: /Users/fanghr/.carton/static/dev.js
- checking Swift compiler path: /Users/fanghr/.carton/sdk/wasm-5.3.0-RELEASE/usr/bin/swift
- checking Swift compiler path: /Users/fanghr/.swiftenv/versions/wasm-5.3.0-RELEASE/usr/bin/swift
- checking Swift compiler path: /Users/fanghr/Library/Developer/Toolchains/swift-wasm-5.3.0-RELEASE.xctoolchain/usr/bin/swift
- checking Swift compiler path: /Library/Developer/Toolchains/swift-wasm-5.3.0-RELEASE.xctoolchain/usr/bin/swift
Inferring basic settings...
- swift executable: /Library/Developer/Toolchains/swift-wasm-5.3.0-RELEASE.xctoolchain/usr/bin/swift
SwiftWasm Swift version 5.3 (swiftlang-5.3.0)
Target: x86_64-apple-darwin20.2.0

Parsing package manifest: /Library/Developer/Toolchains/swift-wasm-5.3.0-RELEASE.xctoolchain/usr/bin/swift package dump-package
- test bundle to run: /Volumes/Data 2/Projects/swiftWASMExample/.build/wasm32-unknown-wasi/debug/swiftWASMExamplePackageTests.wasm

Building the test bundle before running the test suite...
Compiling.../Library/Developer/Toolchains/swift-wasm-5.3.0-RELEASE.xctoolchain/usr/bin/swift build -c debug --product swiftWASMExamplePackageTests --enable-test-discovery --triple wasm32-unknown-wasi -Xswiftc -color-diagnostics
Compilation failed.

 swiftWASMExampleTests.swift  /Volumes/Data 2/Projects/swiftWASMExample/Tests/swiftWASMExampleTests/swiftWASMExampleTests.swift:17

   NOTE   cannot find 'Process' in scope
  17 |         let process = Process()
     |                        ^

   NOTE   cannot find 'Pipe' in scope
  20 |         let pipe = Pipe()
     |                     ^

   NOTE   value of type 'Bundle' has no member 'bundleURL'
  40 |         return Bundle.main.bundleURL
     |                             ^
```

**Comment by MaxDesiatov** [comment]
@chfanghr thank you for reporting this issue. `Process`, and `Pipe` APIs are not available for WebAssembly, as new processes can't be launched from the browser. As for the `LinkError` issue, I guess you're using JavaScriptKit 0.9.0, does specifying exact requirement on 0.8.0 resolve the issue for you?

Also, is the source code for your project available publicly? This would make it much easier to investigate the issue.

**Comment by chfanghr** [comment]
I check my `Package.swift`, JavaScriptKit is specified to 0.8.0:
![image](https://user-images.githubusercontent.com/40087668/101026916-6e8b3600-35b2-11eb-9882-58ce1e690aac.png)

As for source code, it's *just* a project created by `carton init` without any modification:
![image](https://user-images.githubusercontent.com/40087668/101027158-b90cb280-35b2-11eb-93c4-05d18ffdff3a.png)

**Comment by chfanghr** [comment]
But the `Package.resolve` shows that I'm using 0.9.0. That's so wierd.
![image](https://user-images.githubusercontent.com/40087668/101027582-23255780-35b3-11eb-8723-eef07eef0b35.png)
Working on re-resolve the swift package to see if it works.

**Comment by MaxDesiatov** [comment]
I apologize for this bug, the reason is that we need JavaScriptKit releases to coincide with new releases of `carton` that update the JavaScriptKit runtime bits, which didn't happen as quickly with this release. If you use `[upToNextMajor(from:)`](https://developer.apple.com/documentation/swift_packages/package/dependency/requirement/2878218-uptonextmajor) instead of `from:` in your Package.swift for JavaScriptKit, that should solve the issue. But then when the next version of `carton` is released (really soon, this week or next week), you'll have to change that back so that you use JavaScriptKit 0.9.0, instead of 0.8.0.

Again, this experience should be much more smooth, but it's done this way right due to boring technical limitations.

**Comment by chfanghr** [comment]
So I modify the `Package.swift` according to your instruction:
```swift
.package(name: "JavaScriptKit", url: "https://github.com/swiftwasm/JavaScriptKit", .upToNextMajor(from: "0.7.2"))
```
but SPM still resolve the JavaScriptKit at 0.9.0. Maybe I should wait for the next release of carton?

**Comment by MaxDesiatov** [comment]
0.7.2 is too old I think. Sorry for the confusion, `upToNextMinor` should work, or `exact`, `upToNextMajor` still would include 0.9.0.

**Comment by MaxDesiatov** [comment]
`.upToNextMinor(from: "0.8.0")` works locally for me. Does it resolve your issue?

**Comment by chfanghr** [comment]
No. Still LinkError.

**Comment by MaxDesiatov** [comment]
@kateinoigakukun would you be able to help here? I'm running out of ideas...

**Comment by MaxDesiatov** [comment]
@chfanghr BTW, running apps that depend on JavaScriptKit with `wasmer` won't work, it requires browser environments. Also, did you verify that your `Package.resolved` has JavaScriptKit 0.8.0 right now?

**Comment by chfanghr** [comment]
In `Package.swift`:
```swift
.package(name: "JavaScriptKit", url: "https://github.com/swiftwasm/JavaScriptKit", .upToNextMajor(from: "0.8.0"))
```
In `Package.resolved`:
```json
{
  "object": {
    "pins": [
      {
        "package": "JavaScriptKit",
        "repositoryURL": "https://github.com/swiftwasm/JavaScriptKit",
        "state": {
          "branch": null,
          "revision": "b7a02434c6e973c08c3fd5069105ef44dd82b891",
          "version": "0.9.0"
        }
      }
    ]
  },
  "version": 1
}
```

**Comment by chfanghr** [comment]
Had removed `.build` and `Package.resolved` right before `carton bundle`

**Comment by chfanghr** [comment]
I initialized a new project to make sure the issue can be reproduced. Here is what I did:
```bash
mkdir SwiftWasmIssue2284
cd SwiftWasmIssue2284
carton init
vim Package.swift # from: "0.8.0" => .upToNextMajor(from: "0.8.0")
carton bundle
cd Bundle
python3 -m http.server 8088
```
Then in Safari:
```
[Error] LinkError: import function javascript_kit:swjs_call_throwing_new must be callable

	h (c0425cd00dfa149a.js:1:184252)
	promiseReactionJob
```
And Chrome:
```
content-script.js:95 Failed to get subsystem status for purpose {rejected: true, message: {…}}
DevTools failed to load SourceMap: Could not load content for chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
content.js:27 AudioPick(http://127.0.0.1:8088/): Requesting default_no ...
favicon.ico:1 GET http://127.0.0.1:8088/favicon.ico 404 (File not found)
content-script.js:95 Failed to get subsystem status for purpose {rejected: true, message: {…}}
content.js:27 AudioPick(http://127.0.0.1:8088/): Received default_no: 3
content.js:27 AudioPick(http://127.0.0.1:8088/): Inspecting Devices: 2 device(s) total (audio/video input/output)
content.js:27 AudioPick(http://127.0.0.1:8088/): No sinks found
127.0.0.1/:1 Error handling response: TypeError: Cannot read property 'shortcuts' of undefined
    at s (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:1:550)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:1:4838
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:1:10227
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:1:15272
c0425cd00dfa149a.js:1 LinkError: WebAssembly.instantiate(): Import #4 module="javascript_kit" function="swjs_call_throwing_new" error: function import requires a callable
h @ c0425cd00dfa149a.js:1
Promise.catch (async)
(anonymous) @ c0425cd00dfa149a.js:1
r @ c0425cd00dfa149a.js:1
(anonymous) @ c0425cd00dfa149a.js:1
(anonymous) @ c0425cd00dfa149a.js:1
```

**Comment by MaxDesiatov** [comment]
Does `carton dev` work for you in this project?

**Comment by MaxDesiatov** [comment]
Also, I see you mentioned `upToNextMajor`, that will still pull 0.9.0. You have to use to use `exact` or `upToNextMinor` requirement instead of `upToNextMajor`.

**Comment by chfanghr** [comment]
`carton dev` doesn't work.

**Comment by MaxDesiatov** [comment]
I see, it won't work as long as you have JavaScriptKit 0.9.0 in `Package.resolved`. If you use `exact` or `upToNextMinor` requirement instead of `upToNextMajor`, does that resolve your issue?

**Comment by chfanghr** [comment]
Replace `from: "0.8.0"` by `.exact("0.8.0")` work for me! 😆

**Comment by chfanghr** [comment]
So this issue is caused by carton's template project, right?

**Comment by chfanghr** [comment]
btw, `carton test` still failed with the smae log I posted before.

**Comment by MaxDesiatov** [comment]
Awesome! I'll keep the issue open as a reminder for us that we need to find a better way to distribute the JavaScriptKit runtime separately from `carton`.

> So this issue is caused by carton's template project, right?

At the moment yes, because the current version of `carton` ships JavaScriptKit 0.8.0 runtime. The next version of `carton` will ship the latest runtime, and the issue will no longer be reproducible with the latest versions. But a proper solution for this would be to separate the runtime bits, probably distributing them as SwiftPM resources.

> btw, `carton test` still failed with the smae log I posted before.

`carton test` runs tests in `wasmer` by default, which doesn't support projects with JavaScriptKit. If you remove `import JavaScriptKit`, and maybe `JavaScriptKit` dependencies too from targets included in your tests, I think that would resolve the issue with `carton test`. Next version of `carton` will enable running tests in browsers directly, with full support for JavaScriptKit and whatever else you'd want to test in browser environments.

**Comment by MaxDesiatov** [comment]
@chfanghr `carton` 0.9.0 is now available, which you can get on macOS with `brew upgrade` or `brew install swiftwasm/tap/carton` if you don't have it installed via Homebrew. You then will need to bump the version of JavaScriptKit to 0.9.0 in your `Package.swift`, but this will give you access to the latest features introduced in those versions. Again, sorry for the inconvenience.

**Comment by chfanghr** [comment]
Thanks for your help! I'll try the new version instantly.

**Comment by chfanghr** [comment]
`carton init; carton dev` worked perfectly and `Hello World` showed in my browser console without any error. As for  `carton test`, the basic template still incorrectly contains use of `Process`, `Pipe` and so on in test code, which caused failure at the compile stage.

**Comment by MaxDesiatov** [comment]
Thanks for the update! The testing code in the templates is clearly wrong. I'm going to rework how templates work in the next version of `carton` with https://github.com/swiftwasm/carton/issues/91, and will also clean up the testing code if that makes sense?

**Comment by chfanghr** [comment]
Anything I can help with? I would love to contribute.

**Comment by MaxDesiatov** [comment]
Sure, I've just created [a new template repository](https://github.com/swiftwasm/browser-basic-template), it would be great to use it in `carton` instead of the current one generated with `swift package init`. This one has a better introduction with handy links for beginners, and also has a basic test suite that compiles 🙂

We also need to set up a similar template repository for [Tokamak](https://tokamak.dev), and then [adjust the templates infrastructure in `carton`](https://github.com/swiftwasm/carton/blob/main/Sources/carton/Model/Template.swift) to fetch those templates (as archive downloads are available for all repositories, e.g. https://github.com/swiftwasm/browser-basic-template/archive/main.zip) and unpack them instead of using `swift package init`. Does that make sense?

Let me know if you prefer to work on something different, or if you stumble upon any problems.
