### ISSUE TITLE
Use WASILibc's `mman.h` - need to provide compilation flags to WASI and linker flags, how to?

### ISSUE THREAD

**Issue by Sajjon** [swiftwasm/swift#2315]
Hey! Thanks for an amazing project!

I'm trying to get [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) to build and use it in some example/playgroundish Swift Package, lets call it _SwiftWasmTestUsingCryptoSwift_

I've managed to get _CryptoSwift_ to compile and got some functionality working. Trying to get the last pieces of the puzzle to work, which is memory lock and unlock functions (`mlock` and `munlock` which is part of `mman.h`.

I've managed to expand environment in [`SecureBytes.swift`](https://github.com/krzyzanowskim/CryptoSwift/blob/master/Sources/CryptoSwift/SecureBytes.swift) with `#elseif canImport(WASILibc)` however the `mman.h` file is not present when I try to build my fork of CryptoSwift, with command

```bash
swift build --triple wasm32-unknown-wasi
``` 

**I get a compilation error:**

```bash
wasm-ld: error: ./.build/wasm32-unknown-wasi/debug/CryptoSwift.build/SecureBytes.swift.o: undefined symbol: mlock
wasm-ld: error: ./.build/wasm32-unknown-wasi/debug/CryptoSwift.build/SecureBytes.swift.o: undefined symbol: munlock
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
[14/15] Linking SwiftWasmTestUsingCryptoSwift.wasm
```

The [`mman.h` file on in WebAssembly's Github Repo](https://github.com/WebAssembly/wasi-libc/blob/master/libc-top-half/musl/include/sys/mman.h#L2-L3) states:

```header
#ifndef _WASI_EMULATED_MMAN
#error "WASI lacks a true mmap; to enable minimal mmap emulation, \
compile with -D_WASI_EMULATED_MMAN and link with -lwasi-emulated-mman"
#else
```

So seems like I need to:    
  1) Compile WASILibc (?) with the `D_WASI_EMULATED_MMAN` flag somehow?    
  2) Link WASILibc(?) with `-lwasi-emulated-mman` flag somehow?

I am a little bit confused right now as how to do `1)` and `2)`

I can think of four alternatives:    
  1) Add flag(s) to `swift build` command?
  2) Add  [`CSetting`](https://developer.apple.com/documentation/swift_packages/csetting) and/or [`LinkerSetting`](https://developer.apple.com/documentation/swift_packages/linkersetting) to the `Package.swift` file of my fork of _CryptoSwift_
  3) Analog but not to the `Package.swift` file of my fork of _CryptoSwift_, but rather in the `Package.swift` of my example package _SwiftWasmTestUsingCryptoSwift_, 
  4) Some combination of all three?

Any help would be much appreciated!

**Comment by MaxDesiatov** [comment]
As far as I remember, WASILibc is already compiled with those flags.

>     1. Add flag(s) to `swift build` command?
> 
>     2. Add  [`CSetting`](https://developer.apple.com/documentation/swift_packages/csetting) and/or [`LinkerSetting`](https://developer.apple.com/documentation/swift_packages/linkersetting) to the `Package.swift` file of my fork of _CryptoSwift_
> 
>     3. Analog but not to the `Package.swift` file of my fork of _CryptoSwift_, but rather in the `Package.swift` of my example package _SwiftWasmTestUsingCryptoSwift_,

Did you try any of these yet? I think 2. would be the best option long term, when upstreamed for other people to benfit from the fix, if it actually works.

**Comment by kateinoigakukun** [comment]
Unfortunately, `wasi-libc` doesn't provide mlock implementation, so we can't use it. With wasi-libc memory allocator, page I/O can't be controlled because it depends on Wasm host environment

**Comment by Sajjon** [comment]
I tried in `Package.swift` of **_both_** consumer **_and_** dependency (my fork of _CryptoSwift_)

```swift
      .target(
            .....
            linkerSettings: [
                .unsafeFlags(
                    [
                        "-lwasi-emulated-mman",
                    ],
                    .when(platforms: [.wasi])
                )
            ]
        ),
```

But that did not work:

```bash
swift build --triple wasm32-unknown-wasi

wasm-ld: error: /.build/wasm32-unknown-wasi/debug/CryptoSwift.build/SecureBytes.swift.o: undefined symbol: mlock
wasm-ld: error: /.build/wasm32-unknown-wasi/debug/CryptoSwift.build/SecureBytes.swift.o: undefined symbol: munlock
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

**Comment by Sajjon** [comment]
> Unfortunately, `wasi-libc` doesn't provide mlock implementation, so we can't use it. With wasi-libc memory allocator, page I/O can't be controlled because it depends on Wasm host environment

Ok thanks! I suspect as much, that it was a bit too "low level" (too host env dependent).

**Comment by Sajjon** [comment]
💡 Improvement suggestion: @MaxDesiatov  Maybe you can add to the GitBook / Readme / Tutorials how to specify flags in general?

**Comment by MaxDesiatov** [comment]
We didn't have a need for such flags so far, and the way to specify them is already given in SwiftPM docs for `CSetting` and `LinkerSetting` that you linked to. It's not platform-specific really. Would there be a value in duplicating or linking to those docs, if we don't expect an average SwiftWasm developer to have more need for them than an average Swift developer?
