### ISSUE TITLE
Move SIL argument mismatch tweaks to the LLVM IR level

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#2516]
As far as I understand, SIL is supposed to be platform-independnt, so our SIL changes tweaking for caller and callee arguments mismatch won't be accepted upstream (at least on previous attempts they weren't). I think a proper solution would be to check for these mismatches in `IRGen` instead of `SILGen`

 @kateinoigakukun WDYT?

**Comment by kateinoigakukun** [comment]
Yes, we should move target specific things to IRGen ideally. As far as I remember, some SIL functions assume that the target arch allows trailing extra arguments at SIL level, so we need to add a new attribute to limit the max length of arguments.
