### ISSUE TITLE
Package fails to compile when a dependency includes a resource.

### ISSUE THREAD

**Issue by fcanas** [swiftwasm/swift#2568]
A dependency with a resource fails to compile because the `Bundle.module` doesn't seem to be generated when built with the SwiftWASM toolchain. The upstream Swift toolchain works correctly.

The following project fails to compile for me with the errors:
https://github.com/fcanas/swift-wasm-resource-bug

```
> carton dev
   
   ...
   
   ERROR   value of type 'Bundle' has no member 'url'
   ERROR   extraneous argument label 'contentsOf:' in call
   ERROR   initializer 'init(_:)' requires that 'URL' conform to 'Sequence'
  4 |      let url: URL = Bundle.module.url(forResource: "Resource", withExtension: "md")!
    |                                   ^
  5 |      let data: Data = try! Data(contentsOf: url)
    |                            ^   ^
```

I believe the key error is this:

```
ERROR   value of type 'Bundle' has no member 'url'
 4 |      let url: URL = Bundle.module.url(forResource: "Resource", withExtension: "md")!
   |                                   ^
```

Directly building a package with a resource seems to work correctly.

**Comment by MaxDesiatov** [comment]
Making it work with `URL` is a bit complicated for us, we can't infer a hostname upfront.

I think `path(forResource:ofType)` should work, would you be able to use that instead? You can check out [the declaration](https://github.com/swiftwasm/swift-corelibs-foundation/blob/e3391c4465f87c6fb82da73eeb7870157d07163a/Sources/Foundation/Bundle.swift#L441) if you're interested in the internals. Does that resolve the issue for you?

**Comment by fcanas** [comment]
A dependency with a resource fails to have its resources copied by `carton bundle`. I've updated the linked repository to show the problem.

This is the output of `carton bundle`:

```
Bundle
├── TopLevelResource.md
├── c78bdf2c8a889c8f.wasm
├── c9143f6becf19317.js
├── index.html
└── swift-wasm-resource-bug_swift-wasm-resource-bug.resources
    └── TopLevelResource.md
```

I see two potential issues:

1. `TopLevelResource.md` appears twice. Once at the root, and once in a resource directory for the module. The specific resource directory seems more correct, as there could be name collisions across modules.
2. `Resource.md` from the `SubPackageWithResource` package is missing entirely.

**Comment by MaxDesiatov** [comment]
Wrt 1. we only copy resources for the "root" target to the root directory, so I think a collision there is unlikely if possible at all. Copying it to the root for "root" executable targets is to allow things like `Bundle.main` to work.

**Comment by kateinoigakukun** [comment]
This issue will be tracked in swiftwasm/carton repo, so I'll close this thread.
