### ISSUE TITLE
Unable to find system libraries targets that are using pkg-config pc files

### ISSUE THREAD

**Issue by c0diq** [swiftwasm/swift#2918]
When trying to include system libraries, the module cannot be compiled as it can't resolve the path to the libraries pc files. And thus it's not able to add the proper include paths. Strangely it doesn't happen for all libraries. 

System: macOS
Libraries: glfw, cairo installed via brew
Toolchain: Wasm-5.3.1

glfw3.pc is resolved properly, Cairo is not.

Here's a sample project that demonstrates the issue.
[syslib_test.zip](https://github.com/swiftwasm/swift/files/6233089/syslib_test.zip)

```
xcrun --toolchain swiftwasm swift build --target syslib_test --triple wasm32-unknown-wasi
warning: you may be able to install cairo using your system-packager:
    brew install cairo

/syslib_test/Sources/syslib_test/main.swift:1:8: error: no such module 'Ccairo'
import Ccairo
       ^
```

**Comment by kateinoigakukun** [comment]
It seems not a specific issue for our toolchain, so close for now. If you find any issue in wasm toolchain, please feel free to re-open.
