### ISSUE TITLE
`UUID()` does not produce proper UUIDs

### ISSUE THREAD

**Issue by ShonFrazier** [swiftwasm/swift#3320]
Always produces `00000000-0000-4000-8000-000000000000`. This may have been chosen at random (once), but lacks sufficient entropy.

**Comment by yonihemi** [comment]
I've had this happen several months ago but wasn't able to reproduce since. Can you share the setup your seeing this in?
Also, can you try adding `import CoreFoundation` and see if it work?

**Comment by ShonFrazier** [comment]
when importing both Foundation and CoreFoundation I get the same output.

**Comment by ShonFrazier** [comment]
if there's a `TARGET_OS_WASI`, probably just needs to be OR'd with Windows

**Comment by kateinoigakukun** [comment]
Resolved by https://github.com/swiftwasm/swift-corelibs-foundation/pull/323

**Comment by MaxDesiatov** [comment]
TWIMC, the fix has been included in SwiftWasm 5.4.0
