### ISSUE TITLE
Invoke a function passing a string as a parameter?

### ISSUE THREAD

**Issue by onedayitwillmake** [swiftwasm/swift#3895]
I followed along with the excellent reference book (https://book.swiftwasm.org/examples/exporting-function.html), and got something up and running fairly quickly. 

The book gives an example on how to export a function, which can be called from JS:

```swift
@_cdecl("add")
func add(_ lhs: Int, _ rhs: Int) -> Int {
    return lhs + rhs
}
```

The above function accepts 2 `int`s, I naively thought I could modify the function to accept a string using the following:

```swift
@_cdecl("logString")
func logString(_ string:String)  {
  print(string)
}
```

However, I had no such luck. 

Is there a way to pass a string to the exported function?

---

As a work around I'm currently placing a string in `window.$arg0`, then reading `JSObject.global.$arg0` via `JavascriptKit`, in the function:

```swift
@_cdecl("logString")
func logString()  {
  print(JSObject.global.$arg0)
}
```

Although the work around. does work, I'm sure there is a better way that I'm not stumbling onto just yet.

**Comment by kateinoigakukun** [comment]
@onedayitwillmake Thank you for trying!
In Wasm, all exported functions should accept only integers and floating-point numbers.
So most Swift objects (of course including `String`) can not appear in exported function signatures. 
You need to break down such structure into primitive values, for example:

```swift
@_cdecl("logString")
func logString(bytes: UnsafePointer<CChar>)  {
  print(String(cString bytes))
}
```

**Comment by onedayitwillmake** [comment]
@kateinoigakukun Thanks for the tip! That helped a lot!

I had to make a couple of tweaks, I am _almost_ successful, but still had to employ a hack to get it to work.

```swift
@_cdecl("logString")
func logString(_ bytes: UnsafePointer<CChar>)  {
  print("Log string in here! \(bytes)") // logs 0x00000000
  print(String(cString: result!)) // works! Logs "hello"
}

var result:UnsafePointer<CChar>? = nil // storing it in here as a hack worked
@_cdecl("mallocStringHeap")
func mallocStringHeap(length: Int) -> UnsafePointer<CChar> {
  let ptr = malloc(length)
  result = UnsafePointer(ptr!.bindMemory(to: CChar.self, capacity: length))
  return result!
}
```

JS:

```js
  const encoder = new TextEncoder()
  const bytes = encoder.encode('hello')
  const heapMemory = new Uint8Array(exports.memory.buffer);
  const stringPtr = exports.mallocStringHeap(bytes.length)
  for (const [offset, byte] of bytes.entries()) {
    heapMemory[stringPtr + offset] = bytes[offset]
  }

// sample code says `stringHeap`, I took a guess that it was referring to this variable? 
// The value of stringPtr is something like 3672080 so it certainly seems like it could be valid
  exports.logString(stringPtr)
```

I was able to get it to work, although I did have to resort to using a global variable in `main.swift`, Im pretty okay with that since it is working, but i'm curious if there's another way

**Comment by kateinoigakukun** [comment]
Sorry for my late reply. You don't need to retain the allocated pointer because it's not reference counted at all.
