### ISSUE TITLE
Error: undefined symbol: objc_autoreleaseReturnValue

### ISSUE THREAD

**Issue by AugustSaintFreytag** [swiftwasm/swift#4065]
As WebAssembly does not have a built-in `String` type, I'm trying to write a function returning a sequence of `UInt8`, each a byte of a greater UTF-8 string. With toolchain version 5.5.0, even just returning an empty array produces the following error: `wasm-ld: error: …/WASM.build/Command.swift.o: undefined symbol: objc_autoreleaseReturnValue`.

My code for this demo run could hardly be more simple:

```swift
import Foundation

@_cdecl("main")
func main(arg: Int, argc: Int) -> Int {
	exit(0)
}

@_cdecl("greeting")
func greeting() -> [UInt8] {
	return []
}
```

The printout of my toolchain `swift -v`:

```
SwiftWasm Swift version 5.5 (swiftlang-5.5.0)
Target: x86_64-apple-darwin21.2.0
```

**Comment by yonihemi** [comment]
That's not really possible with WebAssembly, at least with the iteration we're using *. The valid function return types are 32int, 64int, 32float and 64float.
A common practice for returning a string is allocating a C String in memory, then returning the pointer from the function. The Javascript environment controls your memory buffer so can reach in and read it. Our [JavascriptKit](https://github.com/swiftwasm/JavaScriptKit) handles both sides of that dance - from JS and from Swift via C.

\* There are some reference type returns enhancements to WebAssembly supported by some browsers but we don't support that yet.

**Comment by AugustSaintFreytag** [comment]
Alright, I appreciate your response, I see that’s not a bug as I first thought — I have to say, getting into a working example of WASM and even just compiling a piece of Swift to run there has been a bit of a struggle. I worked around this it by returning an `UnsafePointer<Int8>` to the `String` and reading from memory on the JS side until the `NULL` termination.

This restriction of unrepresentable types only applies to “exported” functions, right? So any internal logic can still compile with all the types of Swift and the core libs? My main issues currently relate to other types apparently missing from `swiftwasm` like `PropertyListEncoder` or `FileManager`.

**Comment by yonihemi** [comment]
Getting started *is* difficult. The Carton tool and JavaScriptKit will make it easier.
I suggest going through all the sections of the [documentation](https://book.swiftwasm.org/index.html) - it's not that long. The section on [Foundation](https://book.swiftwasm.org/getting-started/porting.html#swift-foundation-and-dispatch) will explain what's missing and why.

**Comment by AugustSaintFreytag** [comment]
Thanks!
