### ISSUE TITLE
ArrayBuffer Error when importing 2 modules with shared dependency

### ISSUE THREAD

**Issue by bitwit** [swiftwasm/swift#4165]
I am trying to import some swift modules I have written and noticed that I get `TypeError: Underlying ArrayBuffer has been detached from the view` as soon as 2 dependencies are added with the same child dependency. 

I don't even have to write `import` statements in my main swift file. The act of declaring them both as dependencies of the target is enough to cause runtime issues despite no compilation warnings.

Is there any workaround for this or is it a known limitation?

**Comment by kateinoigakukun** [comment]
@bitwit Thank you for your report. It's not a known issue.
Could you attach a minimum reproducible project?

**Comment by bitwit** [comment]
Sure thing, I’ll try to prepare this for you. I was using some personal
modules but it would be better to make something small and isolated, like
you suggest.

**Comment by bitwit** [comment]
After doing some more research I think it may be that one of my modules massively increases the binary, maybe beyond what a browser can handle and that's the reason for my issue. I only tested this in a browser context and it was compiling fine.

I have to spend more time piking at each structure but I suspect that complex generic structures may be a culprit.

Is there any guideline around what size of a Wasm file might be too much for the browser? I'm trying to get an idea for how I might better understand the memory limitations in browser.

Otherwise, I think this issue is resolved, not a bug

**Comment by bitwit** [comment]
I think i've discovered the source of my issue and will open a separate ticket
