### ISSUE TITLE
[Possible 5.6 regression] Wasm3 traps running basic tests 

### ISSUE THREAD

**Issue by yonihemi** [swiftwasm/swift#4437]
Wasm3 fails running some basic code that worked in Swiftwasm 5.5:
```swift
print(42)
```
Building with 5.5 and 5.6 toolchains:
```sh
/Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/bin/swiftc math.swift -target wasm32-unknown-wasi -o math-5.5.wasm

wasmer ./math-5.5.wasm
# 42

wasm3 ./math-5.5.wasm
# 42

/Library/Developer/Toolchains/swift-wasm-5.6.0-RELEASE.xctoolchain/usr/bin/swiftc math.swift -target wasm32-unknown-wasi -o math-5.6.wasm

wasmer ./math-5.6.wasm
# 42

wasm3 ./math-5.6.wasm
# Error: [trap] null table element
```
[math.zip](https://github.com/swiftwasm/swift/files/8464261/math.zip)

Note: this is the minimal reproducible test. I've started with this output, which might give a clue: (also code that works in Swiftwasm 5.5)
```
failed to demangle witness for associated type 'Iterator' in conformance 'Swift.Int.Words: Sequence' from mangled name '\u{01} a\u{01}\' - subject type index does not conform to protocol Collection
Error: [trap] unreachable executed
```

**Comment by kateinoigakukun** [comment]
Hmm, there are `468 changed files with 7,302 additions and 4,360 deletions.` ...
https://github.com/swiftwasm/swift/compare/swift-wasm-DEVELOPMENT-SNAPSHOT-2022-03-10-a...swift-wasm-DEVELOPMENT-SNAPSHOT-2022-03-14-a

**Comment by kateinoigakukun** [comment]
Here are produced binaries by https://github.com/swiftwasm/swift/compare/swift-wasm-DEVELOPMENT-SNAPSHOT-2022-03-10-a and swift-wasm-DEVELOPMENT-SNAPSHOT-2022-03-14-a.
[swift-wasm-DEVELOPMENT-SNAPSHOT-2022-03-1x-a.wasm.zip](https://github.com/swiftwasm/swift/files/8474799/swift-wasm-DEVELOPMENT-SNAPSHOT-2022-03-1x-a.wasm.zip)

**Comment by kateinoigakukun** [comment]
OK, it's wasm3's issue for new-style command support https://github.com/wasm3/wasm3/pull/328

**Comment by yonihemi** [comment]
Thanks, amazing work!
Also keeping the bisect tool around for future issues, such a great idea.
