### ISSUE TITLE
Can't use DateFormatter

### ISSUE THREAD

**Issue by leonidasdeim** [swiftwasm/swift#4590]
**Describe the bug**
Can't use DateFormatter at all, I get this error all the time:
```
hello/Sources/hello/main.swift:11:15: error: value of type 'DateFormatter' has no member 'locale'
```

**To Reproduce**
This is my code:
```
import Foundation

let dateFormatter = DateFormatter()
dateFormatter.dateStyle = .medium
dateFormatter.timeStyle = .none
 
let date = Date(timeIntervalSinceReferenceDate: 118800)
 
dateFormatter.locale = Locale(identifier: "en_US")
print(dateFormatter.string(from: date))
```

Building with this command:
```
swift build --triple wasm32-unknown-wasi
```

**Comment by yonihemi** [comment]
Thanks for reporting. DateFormatter, except for rudimentary support, is part of the [missing classes](https://book.swiftwasm.org/getting-started/porting.html#swift-foundation-and-dispatch) in our port of Foundation.
You may want to instead use methods exposed on [JSDate](http://swiftwasm.org/JavaScriptKit/JSDate/#jsdate.tolocaledatestring()) in [JavaScriptKit](https://book.swiftwasm.org/getting-started/javascript-interop.html).
