### ISSUE TITLE
[Question] About 3RD C dynamic library?

### ISSUE THREAD

**Issue by diuming** [swiftwasm/swift#4623]
I have a 3rd c library(for macOS is universal framework(x86_64 and arm64), for Windows is dynamic library .dll).
Currently, It is applied in my standalone Application(wrote by swift) on macOS.

I have a plan to use these c libraries in Web for multi-platforms support(macOS(x86_64 macOS and arm64 macOS) and Windows).

I don't have any concepts about webassembly.
Could I just ask you a question? 
Does the swiftWasm fit for these c libraries for multi-platforms?
thx

**Comment by kateinoigakukun** [comment]
It depends on the library implementation. In general, SwiftWasm supports building C libraries. But if the library expects something outside of the C language feature, you maybe need to patch some parts of the library.
At first, I recommend you to learn the concepts of Wasm and WASI before working on it.
