### ISSUE TITLE
"onCallFunction("missing imported function")" when using wasm3

### ISSUE THREAD

**Issue by ferologics** [swiftwasm/swift#4637]
**Describe the bug**
When using a local convenience or an stdlib function I get `missing imported function` from wasm3

<details> 

<summary>Detailed sample code</summary>

imported print function:
```
@_cdecl("print")
func printFn(pt: UnsafePointer<CChar>, len: Int) {
  c_print(UnsafeMutablePointer(mutating: pt), len)
}
```
this one succeeds
```
@_cdecl("callPrint")
func callPrint() {
  let m = "hello from wasm"
  printFn(pt: m, len: m.utf8.count + 1)
}
```
this one fails with  'missing imported function'
```
@_cdecl("callPrint")
func callPrint() {
  printt("hello from wasm")
}

func printt(_ msg: String) {
  printFn(pt: msg, len: msg.utf8.count + 1)
}
```
</details>

**To Reproduce**
1. Download the [project reproducing the issue](https://github.com/swiftwasm/swift/files/8878094/missing-imp-func.2.zip)
2. Run `testFail()` (compare with `testSuccess()`

**Expected behavior**
Both `callImportedPrint` and `callImportedPrintFailing` should succeed.

**Screenshots**

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/5576161/173044877-3c1717c0-b7f7-4c67-969e-aa5880af984c.png">

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5576161/173044914-a721b734-3594-4d95-9903-4b55ba0af6cc.png">

**Environment:**
 - macOS 12.4 (21F79)
 - Xcode Version 13.3.1 (13E500a)
 - CWasm 0.5.1
 - WasmInterpreter 0.6.1
 - SwiftWasm Swift version 5.6 (swiftlang-5.6.0)
 - Target: arm64-apple-darwin21.5.0

**Additional context**
The `.wasm` was built with the following command:
```
xcrun --toolchain swiftwasm swift build -c release --triple wasm32-unknown-wasi -Xswiftc -Osize -Xlinker --export=print -Xlinker --export=callPrint -Xlinker --export=callPrintFailing -Xlinker --export=callPrintStringInterpolation -Xlinker --export=callPrintStringDescribing
```

**Comment by ferologics** [comment]
Updated [project](https://github.com/swiftwasm/swift/files/8878094/missing-imp-func.2.zip) with additional error test cases:
1. `testStringInterpolationFail()`
2. `testStringDescribingFail()`
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/5576161/173047403-a6df0c54-98cd-4e3a-8b75-b3718e17917c.png">

**Comment by kateinoigakukun** [comment]
Thank you for your detail report! The missing piece is WASI imports.
You need to enable WASI for wasm3. However, the Swift wrapper doesn't provide such API unfortunately...

**Comment by ferologics** [comment]
Hey, thanks for the hint! How would one go about doing this in wasm3? Perhaps you do this in wasmic-ios? AFAIK the WasmInterpreter depends on CWasm, which exposes the wasm3 C interface that I could drop down to if needed.

**Comment by kateinoigakukun** [comment]
You need to call `m3_LinkWASI` like this: https://github.com/kateinoigakukun/wasmic-ios/blob/f52607134f154009b53f30b0edc3cc12038ffa4d/Sources/WasmicWasm/WebAssembly.swift#L57

But it seems CWasm3 doesn't include WASI implementation .c files, so the first step would be adding [`wasi_api.c`](https://github.com/wasm3/wasm3/blob/main/source/m3_api_wasi.c) to the project.

**Comment by ferologics** [comment]
Good news, thanks to your PR's patch both `testStringInterpolationFail()` and `testStringDescribingFail()` test cases no longer trap but succeed 🎉🥇 thanks again for the helpful pointers!

Attaching [updated project](https://github.com/swiftwasm/swift/files/8893387/missing-imp-func.zip) with fully passing tests.

@vshymanskyy can we merge https://github.com/wasm3/wasm3/pull/328 to main?

**Comment by kateinoigakukun** [comment]
That's nice!
