### ISSUE TITLE
Release/backport question

### ISSUE THREAD

**Issue by robbertvanginkel** [swiftwasm/swift#5138]
Thanks for merging in https://github.com/swiftwasm/swift/pull/5079 & https://github.com/swiftwasm/swift-corelibs-foundation/pull/545!

Looking through the toolchains in the releases in the hope that I could find a nightly/snapshot build with those changes incorporated. From the looks of it they should show up in the DEVELOPMENT one once the main builds on the swiftwasm branch are passing, and would be in any future 5.8 release once that comes around?

I couldn't find much on the swiftwasm release/backports process, but as those PRs didn't introduce any new functionality but only fixed up more code that was already available in those versions of swift I was hoping we could backport them onto the 5.7 release branch and get a `swift-wasm-5.7-SNAPSHOT-...` build out for them?

If so, I've opened https://github.com/swiftwasm/swift/pull/5137 / https://github.com/swiftwasm/swift-corelibs-foundation/pull/548. If not and there is some resource on the release process that I missed, please let me know and close the backport prs.

**Comment by kateinoigakukun** [comment]
Good point! We can merge those fixes into the 5.7 release branch 👍

**Comment by kateinoigakukun** [comment]
This release includes your changes! https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.7-SNAPSHOT-2023-01-09-a
