### ISSUE TITLE
Missing Swift 5.9.2 release

### ISSUE THREAD

**Issue by Kyle-Ye** [swiftwasm/swift#5562]
My's package's other platform(eg. Linux, Windows and macOS) is using Swift 5.9.2 for CI. It is a little strange that we only have Swift 5.9.1 for WASM here.

**Comment by kateinoigakukun** [comment]
I am preparing for the next patch release https://github.com/swiftwasm/swiftwasm-build/pull/168

**Comment by kateinoigakukun** [comment]
It's released now https://github.com/swiftwasm/swift/issues/5554#issuecomment-1987137077
