### ISSUE TITLE
DEVELOPMENT-SNAPSHOT in release version

### ISSUE THREAD

**Issue by felixf4xu** [swiftwasm/swift#5566]
Hi,

I downloaded from the release page https://github.com/swiftwasm/swift/releases.

swift-wasm-5.9.1-RELEASE-ubuntu22.04_x86_64.tar.gz:
```
swift --version
SwiftWasm Swift version 5.9.1 (swift-5.9.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```
but, swift-wasm-DEVELOPMENT-SNAPSHOT-2024-02-02-a-ubuntu22.04_x86_64.tar.gz
```
swift --version
Swift version 5.11-dev (LLVM 0c7051c13ba8526, Swift 192d275b78109ff)
Target: x86_64-unknown-linux-gnu
```
So in the DEVELOPMENT-SNAPSHOT, maybe it's not swiftwasm?

**Comment by kateinoigakukun** [comment]
Yes, now the compilers in DEVELOPMENT-SNAPSHOT are just a copy of swift.org/download 's toolchain. No custom changes in the compilers themselves.

**Comment by kateinoigakukun** [comment]
Please re-open this if you need more help
