### ISSUE TITLE
The test executable fails to run due to call stack exhausted (swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-22-a)

### ISSUE THREAD

**Issue by kkebo** [swiftwasm/swift#5573]
## Description

Some test executables fail with the "call stack exhausted" error.

What they have in common:

- they all have many test cases
- the error occurs only when building with the latest (swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-22-a) toolchain
  - swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-20-a doesn't have this issue

## Reproduction

- https://github.com/kkk669/wasm-test-example (almost minimal)
  - [test cases](https://github.com/kkk669/wasm-test-example/blob/main/Tests/WasmTestExampleTests/WasmTestExampleTests.swift) (non-`async`)
  - [steps to build & run](https://github.com/kkk669/wasm-test-example/blob/main/.github/workflows/test.yml)
  - results
    - ❌ [swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-22-a](https://github.com/kkk669/wasm-test-example/actions/runs/8423442736/job/23065079774)
    - ✅ [swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-20-a](https://github.com/kkk669/wasm-test-example/actions/runs/8423442736/job/23065080131)
- https://github.com/kkk669/swift-syntax/pull/18
    - ❌ swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-22-a
    - ✅ swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-20-a

## Expected behavior

I expected the test executable to succeed in running.

In fact, the executable built with the previous (swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-20-a) toolchain has succeeded.

## Environment

- Linux (x86_64, aarch64)
- Swift main snapshot ([swift-DEVELOPMENT-SNAPSHOT-2024-03-20-a](https://github.com/apple/swift/releases/tag/swift-DEVELOPMENT-SNAPSHOT-2024-03-20-a))
- Swift SDK ([swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-22-a](https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-22-a))

**Comment by kateinoigakukun** [comment]
Thank you for detailed reproduction! Between the two snapshots, we introduced significant changes to XCTest to make the change acceptable for the upstream and the change includes how partial async jobs chains during the tests.

For such large scale test suites, we will recommend using tail-call enabled SDK after https://github.com/swiftwasm/swift/issues/5568 will be resolved.

For now, please extend stack size of wasmtime engine and C stack size in wasm binary:
```console
# Extend stack size to 1mb
$ swift build -c release --build-tests --experimental-swift-sdk DEVELOPMENT-SNAPSHOT-2024-03-22-a-wasm -Xlinker -z -Xlinker stack-size=1048576
# 512kb (default) -> 1mb
$ wasmtime --wasm max-wasm-stack=1048576 --dir=/ .build/release/WasmTestExamplePackageTests.wasm
```

**Comment by kkebo** [comment]
> For now, please extend stack size of wasmtime engine and C stack size in wasm binary:

Thank you for providing a workaround. Unfortunately, I had already tried such an approach before I created the issue, but the result was the same. I gave up when I increased the size in stages up to 100 MB.

**Comment by kkebo** [comment]
Oops, I overlooked `--wasm max-wasm-stack=1048576`.

**Comment by kateinoigakukun** [comment]
@kkk669 Note that you need to increase the size of both wasmtime stack size and C stack size just in case.

**Comment by kkebo** [comment]
Thank you so much! The 16 MiB of stack is quite large, but the test is finally working again. I'll go with it until tail-call is ready.

https://github.com/kkk669/swift-syntax/actions/runs/8437995545/job/23109088958
