### ISSUE TITLE
Global Constant Strings Unavailable with Reactor Model

### ISSUE THREAD

**Issue by ejohn-cricut** [swiftwasm/swift#5588]
The `test` function returns 0 when compiled with the reactor model flag. Global constant strings behave as if they are empty. (swift-wasm-5.10.0-RELEASE toolchain)

`Package.swift`
```swift
// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Example",
    targets: [
        .executableTarget(
            name: "Example",
            linkerSettings: [
                .unsafeFlags(
                    [
                        "-Xlinker", "--export=test",
                        "-Xclang-linker", "-mexec-model=reactor",
                    ],
                    .when(platforms: [.wasi])
                )
            ]
        ),
    ]
)

```
`main.swift`
```swift
let testString = "my test string with more than 0 characters"
@_cdecl("test")
public func test() -> Int {
    return testString.count
}

```

**Comment by kateinoigakukun** [comment]
We no longer support top-level expressions in reactor mode. If you really need that, please call `__main_argc_argv` exported function.

**Comment by ejohn-cricut** [comment]
Thanks!

**Comment by cobbal** [comment]
@kateinoigakukun It makes sense that top-level expressions wouldn't work in a library, but this isn't an expression. It's two declarations (by the definitions at https://docs.swift.org/swift-book/documentation/the-swift-programming-language/declarations#Top-Level-Code at least). I would expect top level constants to be initialized in the same manner as static constants in a type.

**Comment by kateinoigakukun** [comment]
@cobbal The r-value of the let declaration statement is an expression that needs to be evaluated at runtime, not compile-time constant.

**Comment by cobbal** [comment]
The r-value isn't a top-level expression. It's part of the "constant declaration". Here's an example of foundation also using them: https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/NSError.swift#L30

For some reason, the foundation global strings do get initialized correctly in the reactor model. I don't see what the difference between them and this is.

**Comment by kateinoigakukun** [comment]
Static properties are initialized lazily at the first access but the top-level variable declarations aren't. Top-level code plays quite special role and is available only in limited places, so I don't recommend that for most situations.

**Comment by cobbal** [comment]
Hmm... This may be related to https://github.com/swiftlang/swift/issues/57991 . Top level let-bindings seem to be handled differently in files named "main.swift".

And if this example is moved to "notmain.swift" (and a blank main.swift is added) then it functions as I would expect.

Having a main.swift for a reactor is a little weird, but I don't know how else to make SPM link everything together into a .wasm file

**Comment by kateinoigakukun** [comment]
Yes, the problem here is reactor should not be executable target.

**Comment by ejohn-cricut** [comment]
Are there any resources on configuring SPM to produce a wasm binary without using an executable target? I haven't found a configuration that works.

Anyhow, I'll close this in favor of the swift issue, seems like that's the root cause.
