### ISSUE TITLE
Investigate if supporting BlocksRuntime is viable

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#658]
This seems to be a requirement for Foundation, related to #592 and #597

**Comment by MaxDesiatov** [comment]
The main culprit right now seems to be the [`_Block_use_RR`](https://github.com/apple/swift-corelibs-foundation/blob/ebf7f50b78e7c5f1e41e2a63bde308c408004d49/Sources/BlocksRuntime/runtime.c#L249) function, which uses either `dlsym` on Linux or process API on Windows. Obviously, neither makes sense on WASI, but I'm not sure what to replace it with.

Foundation actually contains some stubs for libdispatch, but a lot of the APIs are block-heavy. Clang automatically adds a symbol reference to `_NSConcreteStackBlock` from BlocksRuntime to any use of blocks, which then leads to this error during linking:

```
undefined symbol: _NSConcreteStackBlock
```

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Thanks for great investigation!
As far as I saw, it seems `_Block_use_RR` is only used for Objective-C, so can we avoid to use that or link `objc_destructInstance` statically?

**Comment by MaxDesiatov** [comment]
I wasn't able to find a definition of `objc_destructInstance` anywhere and it was puzzling because what definition is used in Windows builds then? Now I'm not so sure Windows builds use that, although the presence of `#if TARGET_OS_WIN32` in Foundation's BlocksRuntime is interesting. Turns out there's a lot of code duplication, there's another [copy of BlocksRuntime in libdispatch](https://github.com/apple/swift-corelibs-libdispatch/blob/80b177209ca6960f42da07121cf86abc59ce3980/src/BlocksRuntime/runtime.c#L263) and [yet another one in LLVM's compiler-rt](https://github.com/llvm/llvm-project/blob/ff9379f4b2d7ebcb8dee94df47dc43c3388f22bf/compiler-rt/lib/BlocksRuntime/runtime.c#L270), the latter one being the most clean without any `objc_destructInstance`. 

Maybe the one from compiler-rt is what we could use, but again, the amount of ifdefs needed in CoreFoundation and Foundation to succesfully compile is staggering, I personally am abandoning my attempts to make Foundation work. I don't think that demand for `NSArray`, `NSDictionary` will be high enough, and `Date`, `Data` and `URL` can be relatively easily reimplemented from scratch without all that cruft (or one could use the existing implementations from [SwiftFoundation](https://github.com/PureSwift/SwiftFoundation/blob/develop/Sources/SwiftFoundation/Date.swift)). 

I think even when we have properly working DCE and LTO, the code size of Foundation and CoreFoundation will still be significant enough in our constrained browser environment, so stuff like `DateFormatter` and `NumberFormatter` probably should be bridged to [browser implementations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) via `JavaScriptKit` to avoid shipping another copy of this functionality reimplemented in C and/or Swift.

The only reason why I wanted to make Foundation work is XCTest, but after having another look at it its use of Foundation seems to be very limited, so I'm currently trying to ifdef that out.

**Comment by karwa** [comment]
> I wasn't able to find a definition of objc_destructInstance anywhere and it was puzzling because what definition is used in Windows builds then? Now I'm not so sure Windows builds use that, although the presence of #if TARGET_OS_WIN32 in Foundation's BlocksRuntime is interesting.

I‘m 99% sure that part of the Windows port is wrong, and that `objc_destructInstance` is a non-public Obj-C runtime method that will only ever _actually_ be found on Darwin platforms. Did you try just using an `#if` to remove that line?

@compnerd does this symbol ever resolve to anything on windows?

**Comment by MaxDesiatov** [comment]
My current conclusion is that Windows uses the implementation from `compiler-rt`, but I don't have a direct confirmation of that. Would be fantastic if Saleem explained how that actually works 🙏

**Comment by compnerd** [comment]
The blocks runtime in foundation is unused everywhere, the canonical definition of blocks runtime resides in libdispatch and most definitely is 100% correct (its been tested is extensively on non-trivial programs which are in production).
