### ISSUE TITLE
Include XCTest in the distribution archive

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swift#922]
I'm able to build XCTest outside of the toolchain build process, this generates the supporting `.swiftmodule`, `.swiftdoc` etc files. The problem is that there's no static archive available for XCTest (`libXCTest.a`) to be linked as a system framework as a result of a `swift build` run in our fork of XCTest. One option is to make it buildable as a part of `build-script` (with CMake as far as I understand), another option is to continue building it with SwiftPM outside of `build-script`, but to enable static library archives in SwiftPM for WASI. I'm currently inclined to do the latter, which could become useful for distributing binary SwiftWasm libraries in general.

**Comment by kateinoigakukun** [comment]
I couldn't build `swiftwasm/swift-corelibs-xctest`. Is the build broken now?

**Comment by MaxDesiatov** [comment]
Sorry about that, that's fixed now. I forgot to change the dependency to the upstream AnyCodable repo instead of my fork, which I deleted today 🤦‍♂️

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Thanks! Now succeeded building. 

> The problem is that there's no static archive available for XCTest (libXCTest.a) to be linked as a system framework as a result of a swift build run in our fork of XCTest. 

I think this is because SwiftPM doesn't support static library emission. So if you want to use SwiftPM build system to build XCTest, you need to support that at first.

BTW can we  use `swift-corelibs-xctest`'s build_script.py? I think it's a better way to avoid bootstrap problem while building toolchain.

**Comment by MaxDesiatov** [comment]
`build_script.py` most probably doesn't use `Package.swift` and SwiftPM, but uses CMake, and therefore probably expects upstream Foundation and Dispatch to be available. I haven't tried it though, I'm having a few additional attempts to build Dispatch for WASI first. 

Another alternative could be enabling static libraries in SwiftPM, at least I was able to get something building locally with manual `swiftc` invocation passing `-emit-library -static` to it. Maybe if I don't get Dispatch working well, I'll try that.

**Comment by kateinoigakukun** [comment]
I see. I know it's really hard to compile Foundation. So I changed my opinion for build_script.py. I think it's easier to support static library distribution for SwiftPM than to use build_script.py. 
If SwiftPM supports that, it's valuable for not only XCTest but also other preinstall libraries.
